import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { FaCartPlus} from "react-icons/fa";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main  className={styles.main}>
        <div className={styles.product_page}>
          <div className={styles.section}>
            {/* <img src="/perfume.jpg" className={styles.product_image} alt="asdf" /> */}
          <Image
                src="/perfume2.jpg"
                alt="Vercel Logo"
                className={styles.product_image}
                width={273}
                height={409}
                priority
              />
          <div className={styles.product_info}>
            <div className={styles.product_category}>PERFUME</div>
            <div className={styles.product_name}>Oudh Agarwood Agalocha Perfume</div>
            <div className={styles.product_description}>This warm, woody scent also known as aoud or oudh is derived from the heart of the agar (or aquilaria) tree.</div>
            <div style={{margin: '35px 0'}}>
            <span className={styles.product_discounted_price}>$79.99</span>
            <span className={styles.product_actual_price}>$99.99</span>
            </div>
            <button className={styles.product_add_to_cart_button}><FaCartPlus />&nbsp; &nbsp; Add to Cart &nbsp; &nbsp;</button>
          </div>
          </div>
        </div>
        <footer className={styles.footer}>
          Product Preview Card Component by&nbsp; <b>MUHAMMAD UMAR</b>
        </footer>
      </main>

    </div>
  )
}

